### ISSUE TITLE
Package deprecation

### ISSUE THREAD

**Issue by mortenpi** [IainNZ/BaseTestNext.jl#13]
[pkg.julialang.org](http://pkg.julialang.org/) lists this package as "deprecated". That's not the case, right?

**Comment by tkelman** [comment]
All tagged version have an upper bound of Julia 0.5. Ref https://github.com/JuliaCI/PackageEvaluator.jl/issues/137#issuecomment-236641373 for how the "deprecated" classification is made. We may want to adjust the wording or include more details on that.

**Comment by mortenpi** [comment]
Thanks for the ref! I am wondering though, is there a reason why there is an upper bound? Currently the package won't install when trying to test on the nightly.

**Comment by tkelman** [comment]
It's redundant with `Base.Test` on Julia 0.5

**Comment by mortenpi** [comment]
You mean that since the functionality is available in 0.5+ then there's no reason to allow its installation? You can't put it into `test/REQUIRE` if you also want to test your package against the master though. Afaict, you would have to have a version checked `Pkg.add` in runtests in this case, which doesn't seem that nice.

**Comment by IainNZ** [comment]
Yeah that seems like a valid complaint. I'm not sure why I did this. More worryingly, this is probably at least a bit out of sync with Base.Test

**Comment by tkelman** [comment]
Yeah given the lack of julia-version-conditional dependencies (without making separate branches of your package for different julia versions), probably better to leave off the upper bound here.

**Comment by mortenpi** [comment]
:tada:

It could still use a tag in METADATA though. Is there something that would stop the current master from being tagged?

**Comment by tkelman** [comment]
No, judging by https://github.com/JuliaCI/BaseTestNext.jl/compare/v0.2.1...master I'd say no. Sorry this fell off the radar, I get way too many notifications and forget about some.
