### ISSUE TITLE
Unify `@testset` and `@testloop` ?

### ISSUE THREAD

**Issue by bicycle1885** [IainNZ/BaseTestNext.jl#6]
The new testing framework is really great, but I thought that `@testset` and `@testloop` can be unified into a single macro. For example, the latter can be interpreted like `@testloop`:

``` julia
@testset begin
    @test ...
end

@testset for i in 1:10
    @test ...
end
```

Since macros can detect the type of given expression block, I think rewriting `@testset for ...` to a loop test is not so difficult.

**Comment by IainNZ** [comment]
Could you open this on Julia itself? It is a good point!

**Comment by bicycle1885** [comment]
I opened an issue at https://github.com/JuliaLang/julia/issues/14011 :smiley:

**Comment by IainNZ** [comment]
This was done (and its great!)
