### ISSUE TITLE
test_approx_eq not counted if passed

### ISSUE THREAD

**Issue by juliangehring** [IainNZ/BaseTestNext.jl#9]
If a test in `@test_approx_eq` and `@test_approx_eq_eps` passes, it does not seem to be counted as a test case:

``` julia
@testset "Foo1" begin
    @test_approx_eq 1 1
end

@testset "Foo2" begin
    @test_approx_eq 1 2
end
```

`Foo1` counts no test, while `Foo2` reports one failed test, as expected. `@test_approx_eq_eps` behaves equivalently.

> Test Summary: | 
> Foo1          | No tests
> 
> Test Summary: | Error  Total
> Foo2          |     1      1

**Comment by IainNZ** [comment]
These "legacy" testing functions are not part of the new `@testset` functionality, as documented here:
http://docs.julialang.org/en/latest/stdlib/test/#other-test-macros

The right place to file issues about `Base.Test` is at `JuliaLang/julia`, this repository just mirrors that.
